// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCU1ZtxwQ0E9shoknWMVW7p8hiZWHa2Y',
    appId: '1:718421263049:web:7598166d3f4cd2efc84318',
    messagingSenderId: '718421263049',
    projectId: 'nevada-alpr-upc',
    authDomain: 'nevada-alpr-upc.firebaseapp.com',
    storageBucket: 'nevada-alpr-upc.appspot.com',
    measurementId: 'G-J9NH3P0WEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDE6pwhck-61dAOiwhk616KYxa2ebCtZU',
    appId: '1:718421263049:android:45dd31f3927b3ba8c84318',
    messagingSenderId: '718421263049',
    projectId: 'nevada-alpr-upc',
    storageBucket: 'nevada-alpr-upc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTxXydARvI77a-JHqcOHVaEGY61tpj3o',
    appId: '1:718421263049:ios:6f5e072d52661d45c84318',
    messagingSenderId: '718421263049',
    projectId: 'nevada-alpr-upc',
    storageBucket: 'nevada-alpr-upc.appspot.com',
    androidClientId: '718421263049-0i3o77jfsbp1jckhlfict9utls5glrjg.apps.googleusercontent.com',
    iosClientId: '718421263049-02k5741koldur13bqifnaddotib54qpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.prAlprUpc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWTxXydARvI77a-JHqcOHVaEGY61tpj3o',
    appId: '1:718421263049:ios:64a3f0c2173d18a5c84318',
    messagingSenderId: '718421263049',
    projectId: 'nevada-alpr-upc',
    storageBucket: 'nevada-alpr-upc.appspot.com',
    androidClientId: '718421263049-0i3o77jfsbp1jckhlfict9utls5glrjg.apps.googleusercontent.com',
    iosClientId: '718421263049-lumr8cai301to1g87iqec4ekkbtt5u67.apps.googleusercontent.com',
    iosBundleId: 'com.example.prAlprUpc.RunnerTests',
  );
}
